version: '2'

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_URI: ${{ secrets.MONGO_URI }}
    ports:
      - '27017:27017'
