# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b8bc561089b1e2ed8e9df5f21c1089f6c29d077d278d73abe6485c5c97d0381e2789ef0c2ee73f476b17fa9b56393583d882044dc5d2b88c5a8fe88ecb2b5bf1

test:
  secret_key_base: 2f243af34f39146c90d3bad8f2390dbc32c28f65e8b0cf06e9bab97ed8b0893147d25b7938f968c0e518e53cb35301d1bce72aed8d33c4b9889e8e2ea4ca1580

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
